-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHATxK9Ti9+ad9Ago
ECbxCyte+ndn/t0mqzMPq4rKQZagCgYIKoZIzj0DAQehRANCAASBGITnJAW5DIRE
G877Fd7LgHymZHXx+HnN/03WlPdltXTuNKaULjlZsThCQl9nP67MQUcmZyjNJxIA
PazkNAth
-----END PRIVATE KEY-----