# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
app_store_connect_api_key(
 key_id: ENV["IOS_KEY_ID"],
 issuer_id: ENV["IOS_ISSUER_ID"],
 key_content: ENV["IOS_KEY_FILEPATH"]
)
before_all do
 xcodes(version: "15.2", select_for_current_build_only: true)
end
platform :ios do
 desc "Push a new beta build to TestFlight"
 lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
 end

 desc "Test connection to App Store Connect"
 lane :test_connection do
    require 'spaceship'
    Spaceship::ConnectAPI.login(ENV["IOS_KEY_ID"], ENV["IOS_ISSUER_ID"], key_content: ENV["IOS_KEY_FILEPATH"])
    apps = Spaceship::ConnectAPI::App.all
    UI.message("Connected to App Store Connect")
    UI.message("List of apps: #{apps.map(&:name).join(', ')}")
 end
end

