name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to TestFlight
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_15.2.app'

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Install Fastlane and Bundler
        run: |
          sudo gem install bundler
        working-directory: ios

      - name: Install Gems with Bundler
        run: |
          bundle install
        working-directory: ios

      - name: Check OpenSSL version
        run: openssl version

      - name: Test App Store Connect Connection
        run: bundle exec fastlane ios test_connection
        working-directory: ios
        env:
          IOS_KEY_ID: ${{ secrets.IOS_KEY_ID }}
          IOS_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
          IOS_KEY_FILEPATH: ${{ secrets.IOS_KEY_FILEPATH }}

      - name: Install and Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'  # Specify Flutter version if needed
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install and Update Cocoapods
        run: |
          cd ios
          pod install

      - name: Deploy to TestFlight
        run: |
          cd ios
          bundle exec fastlane ios beta
        env:
          IOS_KEY_ID: ${{ secrets.IOS_KEY_ID }}
          IOS_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
          IOS_KEY_FILEPATH: ${{ secrets.IOS_KEY_FILEPATH }}
