name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to TestFlight
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install Fastlane and Bundler
        run: |
          sudo gem install fastlane
          sudo gem install bundler

      - name: Set up provisioning profiles
        run: |
          echo "${{ secrets.PROVISIONING_PROFILES }}" | base64 --decode > /tmp/MyApp.mobileprovision

      - name: Install and Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install and Update Cocoapods
        run: |
          cd ios
          sudo gem install cocoapods
          pod update

      - name: Deploy to TestFlight
        env:
          IOS_KEY_ID: ${{ secrets.IOS_KEY_ID }}
          IOS_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
          IOS_KEY_FILEPATH: ${{ secrets.IOS_KEY_FILEPATH }}
        run: |
          cd ios
          bundle config set path vendor/bundle
          bundle install
          bundle exec fastlane ios beta
