name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to TestFlight
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_15.2.app'

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane
        run: gem install fastlane

      - name: Print Xcode version
        run: xcrun --show-sdk-path --sdk iphoneos

      - name: Pod install
        run: |
          cd ios
          pod install
          cd ..

      - name: Run Fastlane
        run: |
          cd ios
          fastlane ios beta
          cd ..
        env:
          IOS_KEY_ID: ${{ secrets.IOS_KEY_ID }}
          IOS_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
          IOS_KEY_FILEPATH: ${{ secrets.IOS_KEY_FILEPATH }}