name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print Current Directory After Checkout
        run: echo `pwd`

      - name: List Files After Checkout
        run: ls -la

      - name: Set up Flutter

        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Install Bundler
        run: sudo gem install bundler

      #   - name: Set up API Key for iOS
      #     env:
      #       IOS_SECRET: ${{ secrets.IOS_SECRET }}
      #     run: |
      #       echo "Writing API Key for iOS to file..."
      #       mkdir -p ./ios # Ensure the ios directory exists
      #       echo $IOS_SECRET > ./ios/key.json
      #       cat ./ios/key.json
      #       echo "List files in iOS directory:"
      #       ls -la ./ios

      - name: Get dependencies
        run: flutter pub get

      - name: Install Cocoapods
        run: |
          cd ios
          sudo gem install cocoapods

      - name: Update Cocoapods
        run: |
          cd ios
          pod update

      - name: Deploy to TestFlight
        env:
          #   FASTLANE_USER: ${{ secrets.IOS_SECRET }}
#          IOS_SECRET: ${{ secrets.IOS_SECRET }}
          BUNDLE_PATH: vendor/bundle
          IOS_KEY_ID: ${{ secrets.IOS_KEY_ID }}
          IOS_ISSUER_ID: ${{ secrets.IOS_ISSUER_ID }}
          IOS_KEY_FILEPATH: ${{ secrets.IOS_KEY_FILEPATH }}

        run: |
          cd ios
          bundle config set path vendor/bundle
          bundle install
          bundle exec fastlane ios beta

    #   - name: Deploy to Google Play
    #     env:
    #       GOOGLE_PLAY_JSON_KEY: ${{ secrets.ANDROID_SECRET }}
    #     run: fastlane android deploy
